environment:
  modkey: mod4
  terminal: kitty
  browser: firefox
  wallpaper_dir: /home/foo/wallpapers
  wallpaper_timeout: 60
  os_logo: /home/foo/logos/linux.svg
  theme: ebenezer
  os_logo_icon: 󰌽
  os_logo_icon_color: "#6200EA"
  weather_api_key: foo
  city_id: 1

groups:
  browsers: 
  terminal:  
  editors: 󰘐
  games:   
  files: 󰉋
  win: 󰍲    

groups_layout:
  default: monadtall
  win: tile

startup:
  keyboard_layout: setxkbmap -model abnt2 -layout br && localectl set-x11-keymap br
  pamac: GDK_BACKEND=x11 pamac-tray &
  polkit: /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
  picom: picom --daemon
  nm_applet: nm-applet &
  lock_screen: xautolock -time 10 -locker "python ~/.config/qtile/lock.py" &
  wallpaper_slideshow: $scripts/wallpaper.sh slideshow $wallpaper_dir $wallpaper_timeout &
  dunst: pkill dunst && dunst &


commands:
  screenshot: flameshot gui --clipboard --path ~/Pictures/Screenshots
  screenshot_full: flameshot full --clipboard --path ~/Pictures/Screenshots
  change_wallpaper: $scripts/wallpaper.sh set /home/william/Pictures/Wallpapers/Active
  mixer: kitty "pulsemixer" # another option: pavucontrol
  powermenu: cd $rofi_home/powermenu && bash powermenu.sh
  volume_level: $scripts/volume.sh level
  volume_up: $scripts/volume.sh up
  volume_down: $scripts/volume.sh down
  mute: $scripts/volume.sh mute
  mute_on: $scripts/volume.sh mute_on
  mute_off: $scripts/volume.sh mute_off
  mute_status: $scripts/volume.sh mute_status
  backlight_level: $scripts/backlight.sh level
  backlight_up: $scripts/backlight.sh up
  backlight_down: $scripts/backlight.sh down

floating:
  wm_class:
    - pavucontrol
    - Arandr
    - Blueman-manager
    - Gpick
    - Kruler
    - Sxiv
    - Tor Browser
    - Wpa_gui
    - veromix
    - xtightvncviewer
    - gnome-calculator
  title: []

fonts:
  font: Fira Code Nerd Font Bold
  font_regular: Fira Code Nerd Font Medium
  font_light: Fira Code Nerd Font Light
  font_strong: Fira Code Nerd Font Semibold
  font_strong_bold: Fira Code Nerd Font Bold
  font_icon: Fira Code Nerd Font Medium
  font_size: 14
  font_icon_size: 16

lock_screen:
  command: ~/.config/qtile/lock.py
  timeout: 10
  font_size: 40
  font: Mononoki Nerd Font Bold
  joke_font_size: 17
  joke_font_path: /usr/share/fonts/TTF/MononokiNerdFont-Regular.ttf
  joke_font_path_alt: /usr/share/fonts/liberation/LiberationMono-Bold.ttf
  joke_providers: reddit,icanhazdad
  joke_foreground_color: "#000"
  joke_text_color: "#fff"
  icanhazdad_joke_url: https://icanhazdadjoke.com/
  reddit_joke_url: https://www.reddit.com/r/ProgrammerDadJokes.json
  blurtype: "0x7"
  blank_color: "#00000000"
  clear_color: "#ffffff22"
  default_color: "#9db4c0"
  key_color: "#8a8ea800"
  text_color: "#4BC1CC"
  wrong_color: "#D50000"
  verifying_color: "#41445800"

monitoring:
  default_color: 'fg_normal'
  high_color: 'fg_orange'
  medium_color: 'fg_yellow'
  threshold_medium: 70
  threshold_high: 90
  burn: yes


bar:
  position: 'top'
  widgets:
    - type: 'group_box'
      margin_y: 3
      margin_x: 3
      padding: 3
      borderwidth: 3
      active: fg_normal
      inactive: fg_normal
      this_current_screen_border: bg_topbar_selected
      this_screen_border: fg_blue
      other_current_screen_border: bg_topbar_selected
      highlight_color: bg_topbar_selected
      highlight_method: text
      foreground: fg_normal
      rounded: false
      urgent_alert_method: border
      urgent_border: fg_urgent
    - type: 'separator'
    - type: 'task_list'
    - type: 'window_name'
      max_chars: 20
    - type: 'weather'
    - type: 'spacer'
      length: 10
    - type: 'clock'
    - type: 'spacer'
      length: 10
    - type: 'notification'
    - type: 'spacer'
      length: 'stretch'
    - type: 'thermal'
      sensor:
        threshold_medium: 55
        threshold_high: 65
    - type: 'cpu'
      sensor:
        threshold_medium: 65
        threshold_high: 85
    - type: 'memory'
      sensor:
        threshold_medium: 65
        threshold_high: 85

    - type: 'battery'
    - type: 'volume'
    - type: 'powermenu'
    - type: 'hidden_tray'
    - type: 'current_layout'
