name: Qtile tests
run-name: Qtile tests in [${{ github.ref_name }}] @${{ github.actor }}

on: 
  push:
    branches:
      - main
      - nightly
    paths:
      - 'qtile/**'
  pull_request:
    branches:
      - main
      - nightly
    paths:
      - 'qtile/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
      working-directory: ./qtile

    - name: Install dependencies
      run: |
        make install
      working-directory: ./qtile

    - name: Required aliases
      run: |
        ln -sf $(pwd)/qtile /home/runner/.config/qtile

    - name: Run ci
      run: |
        make ci
      working-directory: ./qtile
