name: Qtile tests
run-name: Qtile tests in [${{ github.ref_name }}] @${{ github.actor }}

on: 
  push:
    branches:
      - main
      - nightly
    paths:
      - 'qtile/**'
  pull_request:
    branches:
      - main
      - nightly
    paths:
      - 'qtile/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
      working-directory: ./qtile

    - name: Install dependencies
      run: |
        make install
      working-directory: ./qtile

    - name: Run check
      run: |
        make check
      working-directory: ./qtile
